# ===============================
# Monetachi Config Example
# ===============================

# -------------------------------
# Public wallets (read-only)
# -------------------------------
[[wallet]]
chain = "tron"
addr  = "TXXXXXXXXXXXXXXXXXXXX1"

[[wallet]]
chain = "tron"
addr  = "TXXXXXXXXXXXXXXXXXXXX2"

[[wallet]]
chain = "solana"
addr  = "BXXXXXXXXXXXXXXXXXXXX3"

# -------------------------------
# Offline / manual tokens
# -------------------------------
[walletOffline]  # token_id must match CoinGecko API naming
dogecoin    = 50
tether      = 100
shiba-inu   = 1000
usd-coin    = 200
ethereum    = 1.5

# -------------------------------
# API Keys (if required)
# -------------------------------
[apikey]
trongrid = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
